### PR TITLE
Add starter pack submodule and update build script

### PR DESCRIPTION
**Pull request by jbcdnr**
- New directory organisation with each deck of slides in `decks/` as a submodule so the deck of slides can remain private
- And a very [quick start template repository](https://github.com/jbcdnr/slides--starter-pack) with instructions to quickly create a new deck ;)

### CODE REVIEW

**Comment by tvogels** [comment]
Thanks for the PR! I see why you'd want to separate this project from the slide deck.
I'm debating whether submodules for decks are the way to go. Maybe it's better to 'install' slides on your system as a software package / module and then use it in a deck. What do you think?

**Comment by jbcdnr** [comment]
Yes I am not a big fan of submodules, probably because I break them too often...

I don't like so much installing a package, I prefer to clone the repo and use it. Especially if I want to update some things in the module. 

I could go with a separate directory for each deck at the same level as `slides`. It's a bit hacky but it's dead simple. With a very clear error message if `../slides/` does not exist to remind me to clone this repo there, I think it would be user friendly.

**Comment by tvogels** [comment]
Do you prefer multiple decks in this repo? Or just fork this thing for each
deck? I think I’d prefer that, as each deck may also depend on a different
version of the code

**Comment by jbcdnr** [comment]
> as each deck may also depend on a different version of the code

Good point!

Then it would be perfect to make this repo a template (so that we can copy it privately instead of forking). And maybe adding a sketch file to start quickly ;)

What do you think?

**Comment by tvogels** [comment]
> Then it would be perfect to make this repo a template (so that we can copy it privately instead of forking). And maybe adding a sketch file to start quickly ;)

That sounds nice. Forking would have the benefit that you can still contribute framework edits to the main repo (with cherry-pick)

Do you want to update this PR and add your starter kit?

**Comment by jbcdnr** [comment]
I had a second thought on this: what do you think of creating a template starter pack with this repo as a submodule, a bit like the `ext/` folder of dependencies in [nanoGUI](https://github.com/wjakob/nanogui). I think it solves all the problems we mentioned above:

- it's clone and play
- the deck of slides can be private
- a deck of slide is bound to a certain version of the library and will always work
- you can still contribute to the upstream when changing the submodule

**Comment by tvogels** [comment]
With only one slide deck as a submodule, it could work. I guess the benefit of the submodule is cleaner contributing to `slides`?

I guess the process would be: check out the repo, remove the template submodule, create a repo for your slides, add that one instead. Not really clone & play?

**Comment by jbcdnr** [comment]
I was thinking the opposite. Having a repo to clone for each new deck of slides and inside having a `slides/` directory (submodule) containing this library.

**Comment by jbcdnr** [comment]
The process would be, "template" clone the repo in your github, clone it on your laptop and you are ready to update slides.

**Comment by tvogels** [comment]
Ah yes, I didn't read your post carefully. That makes much more sense. Yes, let's do it like that!

**Pull request closed without merging**
